version: '2'

services:

  influxdb:
    image: influxdb

  telegraf:
    image: telegraf
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  app:
    build: app
    environment:
      - FLASK_DEBUG=True
      - STATSD=telegraf
    ports:
      - 5555:5000
